Block model
Lin69/TP_Layout_template_engine pull request #5
Opened 2019-11-13 13:10 UTC by Arugaf

2019-11-13 13:19 UTC, leshiy1295 reviewed
пока с момента РК ничего не поправлено
нужно поправить все замечания (в отмеченных и во всех аналогичных местах)
после всех исправлений можете запросить повторную итерацию ревью

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.cpp
> +void Object::set_class(const std::string &__class) {
в C++ принят camelCase

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.cpp
> +void Object::set_id(const std::string &__id) {
__ зарезервированы для стандартной библиотеки...

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.cpp
> +void Object::set_access_key(const char &_access_key) {
кажется, что сейчас Object знает слишком много всего..

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.cpp
> +    return std::__cxx11::string();
почему не просто ""?

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.cpp
> +Img::Img() {
= default

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.cpp
> +
почему все классы в одном файле?

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.h
> +class A_link : public Object {
обсуждали на РК, что стоит вынести отдельные свойства в базовые классы и задействовать множественное наследование, например, для генерации отдельных элементов

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.h
> +//    std::string _style;
комментариев с нерабочим кодом быть не должно

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.h
> +    std::string _class;
не факт, что string для всего Вам хватит

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.h
> +    void set_wrap(const bool& value); // TODO: небулевое значение
???

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Object.h
> +    std::vector<boost::variant<Form, Div, List, Img, A_link, Input, Textarea, Button>> _objects;
тоже обсуждали на РК
использовать boost внутри библиотеки нельзя
тут использовать даже std::variant - плохо из-за крайне большого количества объектов => нужно переделать на ООП
наконец, в header-файле выдавать особенности реализации (vector<variant>) - плохо. Нужно скрывать её с помощью PIMPL

2019-11-13 13:19 UTC, leshiy1295 commented on Model/Tests/Form_related_test.cpp
> +    input.set_type(4);
откуда пользователь должен знать все типы?
что это за магическая константа?

2019-11-18 15:53 UTC, Arugaf commented
Исправил замечания кроме реализации идиомы PIMPL. Не совсем понятно как передать туда шаблонный параметр для вектора.

2019-11-20 11:52 UTC, leshiy1295 requested changes

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/button.h
> +class Button : public FormsRelated, public Object {
непонятно, почему Button наследуется от FormsRelated
и вообще - что такое FormsRelated

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/button_creator.h
> +    virtual std::shared_ptr<Object> CreateObject() override;
какой Object?
почему ButtonCreator тогда, а не ObjectCreator?

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/creator.h
> +    virtual std::shared_ptr<Object> CreateObject() = 0;
лучше просто - Create()
+ почитайте про std::enable_shared_from_this...

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/input.h
> +enum _type {button, checkbox, file_attr, hidden_attr, image, password, radio, reset_attr, submit, text_attr};
не нужно начинать имена с _
лучше используйте в качестве префикса название класса уж

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/list.h
> +    void SetList(const std::vector<std::string>& new_list);
почему List работает с std::string?
и нехорошо передавать в интерфейсе конкретную низкоуровневую структуру данных std::vector <std::string>

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/src/a.cpp
> +A::A() {
= default

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/src/ul.cpp
> +
хотелось бы видеть взаимодействие интерфейсов между собой
просто набор классов не представляет большого интереса конкретно в Вашем случае

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/tests/src/container_test.cpp
> +#include "form.h"
include - в алфавитном порядке

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/tests/CMakeLists.txt
> +#        COMPILE_FLAGS "-Wall -Wextra -Werror -Wpedantic")
почему закомментировано?

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/container.h
> +    void RemoveObject(const int& id);
непонятно, что такое id
и откуда он берётся

2019-11-20 11:52 UTC, leshiy1295 commented on block_model/lib/block_model/include/a.h
> +class A : public Object {
лучше упаковать все эти классы в отдельный namespace
+ добавить butterfly-header-файл, а также сделать то, что обсудили на последнем семинаре

2019-12-07 12:08 UTC, Arugaf commented
На РК 3.

2019-12-15 10:29 UTC, leshiy1295 requested changes
очень много копипасты сейчас...
нужно от этого избавиться, и учесть все замечания/предложения, которые обсудили на РК
после исправлений можете отправить код на повторное ревью

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/CMakeLists.txt
> +#        COMPILE_FLAGS "-Wall -Wextra -Werror -Wpedantic")
почему закомментировано?

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/include/a.h
> +            [[nodiscard]] string MakeHtmlString() const override;
воспринимается как std::string
свои классы нужно писать с большой буквы

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/include/a_creator.h
> +        std::shared_ptr<Object> Create() override;
в последней лекции рассказывалось про enable_shared_from_this

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/include/form.h
> +        void SetHttpMethod(const bool& value = true);
зачем передавать bool по константной ссылке?

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/src/a.cpp
> +    id_attr = ----id_count;
не надо так делать :)

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/src/a.cpp
> +    result + block_model::string("</a>");
если тут всё равно использует namespace, почему бы там определение и не оставить?

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/src/div.cpp
> +    id_attr = ----id_count;
копипаста с тем, что было раньше...

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/src/div.cpp
> +        if (it) {
а тут может быть it == nullptr?

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/src/input.cpp
> +    id_attr = ----id_count;
очень много копипасты - следствие того, что не вынесена базовая часть в отдельные классы, как мы это с Вами обсуждали ещё на РК2...

2019-12-15 10:29 UTC, leshiy1295 commented on block_model/lib/block_model/src/input.cpp
> +    switch (type_attr) {
это совсем не годится - каждый класс должен сам решать, как себя выводить
тут нужно использовать цепочку ответственности

2019-12-21 10:26 UTC, Arugaf commented
К предзащите

2019-12-28 16:39 UTC, leshiy1295 reviewed
Жаль, что в итоге далеко не все замечания были учтены, и не удалось довести проект до рабочего прототипа...

2019-12-28 16:39 UTC, leshiy1295 commented on block_model/lib/block_model/include/container.h
> +        std::list<std::shared_ptr<Object>> objects_content;
ну вот о чём я и говорил - vector поменялся на list, и произошло это в .h-файле, причём в довольно общем...
если бы в .h файле этого не было бы, и использовался бы PIMPL - это не вызвало бы доп. проблем

2019-12-28 16:39 UTC, leshiy1295 commented on block_model/lib/block_model/include/creator.h
> +    static std::pair<std::shared_ptr<Object>, std::shared_ptr<T>> Create() {
использовать pair просто так - плохо
лучше бы сделали отдельную структуру с полями

2019-12-28 16:39 UTC, leshiy1295 commented on block_model/lib/block_model/include/object.h
> +        std::unordered_multimap<std::string, std::string> map;
так и не вынесено из .h-файла...

2019-12-28 16:39 UTC, leshiy1295 commented on block_model/lib/block_model/src/container.cpp
> +            objects_content.remove(it);
remove_if?

2019-12-28 16:39 UTC, leshiy1295 commented on block_model/lib/block_model/src/textarea.cpp
> +    if (this == &src) {
стоило использовать идиому Copy-And-Swap для реализации оператора присваивания

2023-12-05 11:55 UTC, closed without merging